// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Reservation.proto

package via.sep3.databaseserver.protobuff;

/**
 * Protobuf type {@code AcceptMessage}
 */
public final class AcceptMessage extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:AcceptMessage)
    AcceptMessageOrBuilder {
private static final long serialVersionUID = 0L;
  // Use AcceptMessage.newBuilder() to construct.
  private AcceptMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private AcceptMessage() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new AcceptMessage();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private AcceptMessage(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            reservationId_ = input.readInt32();
            break;
          }
          case 16: {

            didAccept_ = input.readBool();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (com.google.protobuf.UninitializedMessageException e) {
      throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return via.sep3.databaseserver.protobuff.Reservation.internal_static_AcceptMessage_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return via.sep3.databaseserver.protobuff.Reservation.internal_static_AcceptMessage_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            via.sep3.databaseserver.protobuff.AcceptMessage.class, via.sep3.databaseserver.protobuff.AcceptMessage.Builder.class);
  }

  public static final int RESERVATIONID_FIELD_NUMBER = 1;
  private int reservationId_;
  /**
   * <code>int32 reservationId = 1;</code>
   * @return The reservationId.
   */
  @java.lang.Override
  public int getReservationId() {
    return reservationId_;
  }

  public static final int DIDACCEPT_FIELD_NUMBER = 2;
  private boolean didAccept_;
  /**
   * <code>bool didAccept = 2;</code>
   * @return The didAccept.
   */
  @java.lang.Override
  public boolean getDidAccept() {
    return didAccept_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (reservationId_ != 0) {
      output.writeInt32(1, reservationId_);
    }
    if (didAccept_ != false) {
      output.writeBool(2, didAccept_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (reservationId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, reservationId_);
    }
    if (didAccept_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(2, didAccept_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof via.sep3.databaseserver.protobuff.AcceptMessage)) {
      return super.equals(obj);
    }
    via.sep3.databaseserver.protobuff.AcceptMessage other = (via.sep3.databaseserver.protobuff.AcceptMessage) obj;

    if (getReservationId()
        != other.getReservationId()) return false;
    if (getDidAccept()
        != other.getDidAccept()) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + RESERVATIONID_FIELD_NUMBER;
    hash = (53 * hash) + getReservationId();
    hash = (37 * hash) + DIDACCEPT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getDidAccept());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static via.sep3.databaseserver.protobuff.AcceptMessage parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static via.sep3.databaseserver.protobuff.AcceptMessage parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static via.sep3.databaseserver.protobuff.AcceptMessage parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static via.sep3.databaseserver.protobuff.AcceptMessage parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static via.sep3.databaseserver.protobuff.AcceptMessage parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static via.sep3.databaseserver.protobuff.AcceptMessage parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static via.sep3.databaseserver.protobuff.AcceptMessage parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static via.sep3.databaseserver.protobuff.AcceptMessage parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static via.sep3.databaseserver.protobuff.AcceptMessage parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static via.sep3.databaseserver.protobuff.AcceptMessage parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static via.sep3.databaseserver.protobuff.AcceptMessage parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static via.sep3.databaseserver.protobuff.AcceptMessage parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(via.sep3.databaseserver.protobuff.AcceptMessage prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code AcceptMessage}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:AcceptMessage)
      via.sep3.databaseserver.protobuff.AcceptMessageOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return via.sep3.databaseserver.protobuff.Reservation.internal_static_AcceptMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return via.sep3.databaseserver.protobuff.Reservation.internal_static_AcceptMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              via.sep3.databaseserver.protobuff.AcceptMessage.class, via.sep3.databaseserver.protobuff.AcceptMessage.Builder.class);
    }

    // Construct using via.sep3.databaseserver.protobuff.AcceptMessage.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      reservationId_ = 0;

      didAccept_ = false;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return via.sep3.databaseserver.protobuff.Reservation.internal_static_AcceptMessage_descriptor;
    }

    @java.lang.Override
    public via.sep3.databaseserver.protobuff.AcceptMessage getDefaultInstanceForType() {
      return via.sep3.databaseserver.protobuff.AcceptMessage.getDefaultInstance();
    }

    @java.lang.Override
    public via.sep3.databaseserver.protobuff.AcceptMessage build() {
      via.sep3.databaseserver.protobuff.AcceptMessage result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public via.sep3.databaseserver.protobuff.AcceptMessage buildPartial() {
      via.sep3.databaseserver.protobuff.AcceptMessage result = new via.sep3.databaseserver.protobuff.AcceptMessage(this);
      result.reservationId_ = reservationId_;
      result.didAccept_ = didAccept_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof via.sep3.databaseserver.protobuff.AcceptMessage) {
        return mergeFrom((via.sep3.databaseserver.protobuff.AcceptMessage)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(via.sep3.databaseserver.protobuff.AcceptMessage other) {
      if (other == via.sep3.databaseserver.protobuff.AcceptMessage.getDefaultInstance()) return this;
      if (other.getReservationId() != 0) {
        setReservationId(other.getReservationId());
      }
      if (other.getDidAccept() != false) {
        setDidAccept(other.getDidAccept());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      via.sep3.databaseserver.protobuff.AcceptMessage parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (via.sep3.databaseserver.protobuff.AcceptMessage) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int reservationId_ ;
    /**
     * <code>int32 reservationId = 1;</code>
     * @return The reservationId.
     */
    @java.lang.Override
    public int getReservationId() {
      return reservationId_;
    }
    /**
     * <code>int32 reservationId = 1;</code>
     * @param value The reservationId to set.
     * @return This builder for chaining.
     */
    public Builder setReservationId(int value) {
      
      reservationId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 reservationId = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearReservationId() {
      
      reservationId_ = 0;
      onChanged();
      return this;
    }

    private boolean didAccept_ ;
    /**
     * <code>bool didAccept = 2;</code>
     * @return The didAccept.
     */
    @java.lang.Override
    public boolean getDidAccept() {
      return didAccept_;
    }
    /**
     * <code>bool didAccept = 2;</code>
     * @param value The didAccept to set.
     * @return This builder for chaining.
     */
    public Builder setDidAccept(boolean value) {
      
      didAccept_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool didAccept = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearDidAccept() {
      
      didAccept_ = false;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:AcceptMessage)
  }

  // @@protoc_insertion_point(class_scope:AcceptMessage)
  private static final via.sep3.databaseserver.protobuff.AcceptMessage DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new via.sep3.databaseserver.protobuff.AcceptMessage();
  }

  public static via.sep3.databaseserver.protobuff.AcceptMessage getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<AcceptMessage>
      PARSER = new com.google.protobuf.AbstractParser<AcceptMessage>() {
    @java.lang.Override
    public AcceptMessage parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new AcceptMessage(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<AcceptMessage> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<AcceptMessage> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public via.sep3.databaseserver.protobuff.AcceptMessage getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

