// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Reservation.proto

package via.sep3.databaseserver.protobuff;

public interface AcceptMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:AcceptMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 reservationId = 1;</code>
   * @return The reservationId.
   */
  int getReservationId();

  /**
   * <code>bool didAccept = 2;</code>
   * @return The didAccept.
   */
  boolean getDidAccept();
}
