// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Reservation.proto

package via.sep3.databaseserver.protobuff;

public interface BoolValueOrBuilder extends
    // @@protoc_insertion_point(interface_extends:BoolValue)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool value = 1;</code>
   * @return The value.
   */
  boolean getValue();
}
