// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Users.proto

package via.sep3.databaseserver.protobuff;

public interface BoolMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:BoolMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool status = 1;</code>
   * @return The status.
   */
  boolean getStatus();

  /**
   * <code>int32 userId = 2;</code>
   * @return The userId.
   */
  int getUserId();

  /**
   * <code>optional int32 licenseNo = 3;</code>
   * @return Whether the licenseNo field is set.
   */
  boolean hasLicenseNo();
  /**
   * <code>optional int32 licenseNo = 3;</code>
   * @return The licenseNo.
   */
  int getLicenseNo();
}
