// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Rides.proto

package via.sep3.databaseserver.protobuff;

public interface ConfirmationMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ConfirmationMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string confirmationMessage = 1;</code>
   * @return The confirmationMessage.
   */
  java.lang.String getConfirmationMessage();
  /**
   * <code>string confirmationMessage = 1;</code>
   * @return The bytes for confirmationMessage.
   */
  com.google.protobuf.ByteString
      getConfirmationMessageBytes();
}
