// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Users.proto

package via.sep3.databaseserver.protobuff;

public interface CreateAccountMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:CreateAccountMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>optional int32 licenseNo = 2;</code>
   * @return Whether the licenseNo field is set.
   */
  boolean hasLicenseNo();
  /**
   * <code>optional int32 licenseNo = 2;</code>
   * @return The licenseNo.
   */
  int getLicenseNo();

  /**
   * <code>int32 phoneNumber = 3;</code>
   * @return The phoneNumber.
   */
  int getPhoneNumber();

  /**
   * <code>string email = 4;</code>
   * @return The email.
   */
  java.lang.String getEmail();
  /**
   * <code>string email = 4;</code>
   * @return The bytes for email.
   */
  com.google.protobuf.ByteString
      getEmailBytes();

  /**
   * <code>string password = 5;</code>
   * @return The password.
   */
  java.lang.String getPassword();
  /**
   * <code>string password = 5;</code>
   * @return The bytes for password.
   */
  com.google.protobuf.ByteString
      getPasswordBytes();
}
