// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Rides.proto

package via.sep3.databaseserver.protobuff;

/**
 * <pre>
 *Probably not needed for now
 * </pre>
 *
 * Protobuf type {@code EpochTimelineMessage}
 */
public final class EpochTimelineMessage extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:EpochTimelineMessage)
    EpochTimelineMessageOrBuilder {
private static final long serialVersionUID = 0L;
  // Use EpochTimelineMessage.newBuilder() to construct.
  private EpochTimelineMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private EpochTimelineMessage() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new EpochTimelineMessage();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private EpochTimelineMessage(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {
            bitField0_ |= 0x00000001;
            epochLowerBound_ = input.readInt64();
            break;
          }
          case 16: {
            bitField0_ |= 0x00000002;
            epochUpperBound_ = input.readInt64();
            break;
          }
          case 24: {

            epochNow_ = input.readInt64();
            break;
          }
          case 32: {

            userId_ = input.readInt32();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (com.google.protobuf.UninitializedMessageException e) {
      throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return via.sep3.databaseserver.protobuff.RidesOuterClass.internal_static_EpochTimelineMessage_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return via.sep3.databaseserver.protobuff.RidesOuterClass.internal_static_EpochTimelineMessage_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            via.sep3.databaseserver.protobuff.EpochTimelineMessage.class, via.sep3.databaseserver.protobuff.EpochTimelineMessage.Builder.class);
  }

  private int bitField0_;
  public static final int EPOCHLOWERBOUND_FIELD_NUMBER = 1;
  private long epochLowerBound_;
  /**
   * <code>optional int64 epochLowerBound = 1;</code>
   * @return Whether the epochLowerBound field is set.
   */
  @java.lang.Override
  public boolean hasEpochLowerBound() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>optional int64 epochLowerBound = 1;</code>
   * @return The epochLowerBound.
   */
  @java.lang.Override
  public long getEpochLowerBound() {
    return epochLowerBound_;
  }

  public static final int EPOCHUPPERBOUND_FIELD_NUMBER = 2;
  private long epochUpperBound_;
  /**
   * <code>optional int64 epochUpperBound = 2;</code>
   * @return Whether the epochUpperBound field is set.
   */
  @java.lang.Override
  public boolean hasEpochUpperBound() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>optional int64 epochUpperBound = 2;</code>
   * @return The epochUpperBound.
   */
  @java.lang.Override
  public long getEpochUpperBound() {
    return epochUpperBound_;
  }

  public static final int EPOCHNOW_FIELD_NUMBER = 3;
  private long epochNow_;
  /**
   * <code>int64 epochNow = 3;</code>
   * @return The epochNow.
   */
  @java.lang.Override
  public long getEpochNow() {
    return epochNow_;
  }

  public static final int USERID_FIELD_NUMBER = 4;
  private int userId_;
  /**
   * <code>int32 userId = 4;</code>
   * @return The userId.
   */
  @java.lang.Override
  public int getUserId() {
    return userId_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeInt64(1, epochLowerBound_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeInt64(2, epochUpperBound_);
    }
    if (epochNow_ != 0L) {
      output.writeInt64(3, epochNow_);
    }
    if (userId_ != 0) {
      output.writeInt32(4, userId_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, epochLowerBound_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(2, epochUpperBound_);
    }
    if (epochNow_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(3, epochNow_);
    }
    if (userId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(4, userId_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof via.sep3.databaseserver.protobuff.EpochTimelineMessage)) {
      return super.equals(obj);
    }
    via.sep3.databaseserver.protobuff.EpochTimelineMessage other = (via.sep3.databaseserver.protobuff.EpochTimelineMessage) obj;

    if (hasEpochLowerBound() != other.hasEpochLowerBound()) return false;
    if (hasEpochLowerBound()) {
      if (getEpochLowerBound()
          != other.getEpochLowerBound()) return false;
    }
    if (hasEpochUpperBound() != other.hasEpochUpperBound()) return false;
    if (hasEpochUpperBound()) {
      if (getEpochUpperBound()
          != other.getEpochUpperBound()) return false;
    }
    if (getEpochNow()
        != other.getEpochNow()) return false;
    if (getUserId()
        != other.getUserId()) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasEpochLowerBound()) {
      hash = (37 * hash) + EPOCHLOWERBOUND_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getEpochLowerBound());
    }
    if (hasEpochUpperBound()) {
      hash = (37 * hash) + EPOCHUPPERBOUND_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getEpochUpperBound());
    }
    hash = (37 * hash) + EPOCHNOW_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getEpochNow());
    hash = (37 * hash) + USERID_FIELD_NUMBER;
    hash = (53 * hash) + getUserId();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static via.sep3.databaseserver.protobuff.EpochTimelineMessage parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static via.sep3.databaseserver.protobuff.EpochTimelineMessage parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static via.sep3.databaseserver.protobuff.EpochTimelineMessage parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static via.sep3.databaseserver.protobuff.EpochTimelineMessage parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static via.sep3.databaseserver.protobuff.EpochTimelineMessage parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static via.sep3.databaseserver.protobuff.EpochTimelineMessage parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static via.sep3.databaseserver.protobuff.EpochTimelineMessage parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static via.sep3.databaseserver.protobuff.EpochTimelineMessage parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static via.sep3.databaseserver.protobuff.EpochTimelineMessage parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static via.sep3.databaseserver.protobuff.EpochTimelineMessage parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static via.sep3.databaseserver.protobuff.EpochTimelineMessage parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static via.sep3.databaseserver.protobuff.EpochTimelineMessage parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(via.sep3.databaseserver.protobuff.EpochTimelineMessage prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   *Probably not needed for now
   * </pre>
   *
   * Protobuf type {@code EpochTimelineMessage}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:EpochTimelineMessage)
      via.sep3.databaseserver.protobuff.EpochTimelineMessageOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return via.sep3.databaseserver.protobuff.RidesOuterClass.internal_static_EpochTimelineMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return via.sep3.databaseserver.protobuff.RidesOuterClass.internal_static_EpochTimelineMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              via.sep3.databaseserver.protobuff.EpochTimelineMessage.class, via.sep3.databaseserver.protobuff.EpochTimelineMessage.Builder.class);
    }

    // Construct using via.sep3.databaseserver.protobuff.EpochTimelineMessage.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      epochLowerBound_ = 0L;
      bitField0_ = (bitField0_ & ~0x00000001);
      epochUpperBound_ = 0L;
      bitField0_ = (bitField0_ & ~0x00000002);
      epochNow_ = 0L;

      userId_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return via.sep3.databaseserver.protobuff.RidesOuterClass.internal_static_EpochTimelineMessage_descriptor;
    }

    @java.lang.Override
    public via.sep3.databaseserver.protobuff.EpochTimelineMessage getDefaultInstanceForType() {
      return via.sep3.databaseserver.protobuff.EpochTimelineMessage.getDefaultInstance();
    }

    @java.lang.Override
    public via.sep3.databaseserver.protobuff.EpochTimelineMessage build() {
      via.sep3.databaseserver.protobuff.EpochTimelineMessage result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public via.sep3.databaseserver.protobuff.EpochTimelineMessage buildPartial() {
      via.sep3.databaseserver.protobuff.EpochTimelineMessage result = new via.sep3.databaseserver.protobuff.EpochTimelineMessage(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.epochLowerBound_ = epochLowerBound_;
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.epochUpperBound_ = epochUpperBound_;
        to_bitField0_ |= 0x00000002;
      }
      result.epochNow_ = epochNow_;
      result.userId_ = userId_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof via.sep3.databaseserver.protobuff.EpochTimelineMessage) {
        return mergeFrom((via.sep3.databaseserver.protobuff.EpochTimelineMessage)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(via.sep3.databaseserver.protobuff.EpochTimelineMessage other) {
      if (other == via.sep3.databaseserver.protobuff.EpochTimelineMessage.getDefaultInstance()) return this;
      if (other.hasEpochLowerBound()) {
        setEpochLowerBound(other.getEpochLowerBound());
      }
      if (other.hasEpochUpperBound()) {
        setEpochUpperBound(other.getEpochUpperBound());
      }
      if (other.getEpochNow() != 0L) {
        setEpochNow(other.getEpochNow());
      }
      if (other.getUserId() != 0) {
        setUserId(other.getUserId());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      via.sep3.databaseserver.protobuff.EpochTimelineMessage parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (via.sep3.databaseserver.protobuff.EpochTimelineMessage) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private long epochLowerBound_ ;
    /**
     * <code>optional int64 epochLowerBound = 1;</code>
     * @return Whether the epochLowerBound field is set.
     */
    @java.lang.Override
    public boolean hasEpochLowerBound() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional int64 epochLowerBound = 1;</code>
     * @return The epochLowerBound.
     */
    @java.lang.Override
    public long getEpochLowerBound() {
      return epochLowerBound_;
    }
    /**
     * <code>optional int64 epochLowerBound = 1;</code>
     * @param value The epochLowerBound to set.
     * @return This builder for chaining.
     */
    public Builder setEpochLowerBound(long value) {
      bitField0_ |= 0x00000001;
      epochLowerBound_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int64 epochLowerBound = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearEpochLowerBound() {
      bitField0_ = (bitField0_ & ~0x00000001);
      epochLowerBound_ = 0L;
      onChanged();
      return this;
    }

    private long epochUpperBound_ ;
    /**
     * <code>optional int64 epochUpperBound = 2;</code>
     * @return Whether the epochUpperBound field is set.
     */
    @java.lang.Override
    public boolean hasEpochUpperBound() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional int64 epochUpperBound = 2;</code>
     * @return The epochUpperBound.
     */
    @java.lang.Override
    public long getEpochUpperBound() {
      return epochUpperBound_;
    }
    /**
     * <code>optional int64 epochUpperBound = 2;</code>
     * @param value The epochUpperBound to set.
     * @return This builder for chaining.
     */
    public Builder setEpochUpperBound(long value) {
      bitField0_ |= 0x00000002;
      epochUpperBound_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int64 epochUpperBound = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearEpochUpperBound() {
      bitField0_ = (bitField0_ & ~0x00000002);
      epochUpperBound_ = 0L;
      onChanged();
      return this;
    }

    private long epochNow_ ;
    /**
     * <code>int64 epochNow = 3;</code>
     * @return The epochNow.
     */
    @java.lang.Override
    public long getEpochNow() {
      return epochNow_;
    }
    /**
     * <code>int64 epochNow = 3;</code>
     * @param value The epochNow to set.
     * @return This builder for chaining.
     */
    public Builder setEpochNow(long value) {
      
      epochNow_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 epochNow = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearEpochNow() {
      
      epochNow_ = 0L;
      onChanged();
      return this;
    }

    private int userId_ ;
    /**
     * <code>int32 userId = 4;</code>
     * @return The userId.
     */
    @java.lang.Override
    public int getUserId() {
      return userId_;
    }
    /**
     * <code>int32 userId = 4;</code>
     * @param value The userId to set.
     * @return This builder for chaining.
     */
    public Builder setUserId(int value) {
      
      userId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 userId = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearUserId() {
      
      userId_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:EpochTimelineMessage)
  }

  // @@protoc_insertion_point(class_scope:EpochTimelineMessage)
  private static final via.sep3.databaseserver.protobuff.EpochTimelineMessage DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new via.sep3.databaseserver.protobuff.EpochTimelineMessage();
  }

  public static via.sep3.databaseserver.protobuff.EpochTimelineMessage getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<EpochTimelineMessage>
      PARSER = new com.google.protobuf.AbstractParser<EpochTimelineMessage>() {
    @java.lang.Override
    public EpochTimelineMessage parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new EpochTimelineMessage(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<EpochTimelineMessage> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<EpochTimelineMessage> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public via.sep3.databaseserver.protobuff.EpochTimelineMessage getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

