// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Users.proto

package via.sep3.databaseserver.protobuff;

public interface LicenseMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:LicenseMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 licenseNo = 1;</code>
   * @return The licenseNo.
   */
  int getLicenseNo();

  /**
   * <code>int32 userId = 2;</code>
   * @return The userId.
   */
  int getUserId();
}
