// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Rides.proto

package via.sep3.databaseserver.protobuff;

public interface LocationMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:LocationMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string country = 1;</code>
   * @return The country.
   */
  java.lang.String getCountry();
  /**
   * <code>string country = 1;</code>
   * @return The bytes for country.
   */
  com.google.protobuf.ByteString
      getCountryBytes();

  /**
   * <code>string city = 2;</code>
   * @return The city.
   */
  java.lang.String getCity();
  /**
   * <code>string city = 2;</code>
   * @return The bytes for city.
   */
  com.google.protobuf.ByteString
      getCityBytes();

  /**
   * <code>string street = 3;</code>
   * @return The street.
   */
  java.lang.String getStreet();
  /**
   * <code>string street = 3;</code>
   * @return The bytes for street.
   */
  com.google.protobuf.ByteString
      getStreetBytes();

  /**
   * <code>string zipcode = 4;</code>
   * @return The zipcode.
   */
  java.lang.String getZipcode();
  /**
   * <code>string zipcode = 4;</code>
   * @return The bytes for zipcode.
   */
  com.google.protobuf.ByteString
      getZipcodeBytes();

  /**
   * <code>double coordinateX = 5;</code>
   * @return The coordinateX.
   */
  double getCoordinateX();

  /**
   * <code>double coordinateY = 6;</code>
   * @return The coordinateY.
   */
  double getCoordinateY();
}
