// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Reservation.proto

package via.sep3.databaseserver.protobuff;

public interface ReservationsToAcceptCollectionOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ReservationsToAcceptCollection)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .ReservationMessage reservationMessages = 1;</code>
   */
  java.util.List<via.sep3.databaseserver.protobuff.ReservationMessage> 
      getReservationMessagesList();
  /**
   * <code>repeated .ReservationMessage reservationMessages = 1;</code>
   */
  via.sep3.databaseserver.protobuff.ReservationMessage getReservationMessages(int index);
  /**
   * <code>repeated .ReservationMessage reservationMessages = 1;</code>
   */
  int getReservationMessagesCount();
  /**
   * <code>repeated .ReservationMessage reservationMessages = 1;</code>
   */
  java.util.List<? extends via.sep3.databaseserver.protobuff.ReservationMessageOrBuilder> 
      getReservationMessagesOrBuilderList();
  /**
   * <code>repeated .ReservationMessage reservationMessages = 1;</code>
   */
  via.sep3.databaseserver.protobuff.ReservationMessageOrBuilder getReservationMessagesOrBuilder(
      int index);
}
