// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Reservation.proto

package via.sep3.databaseserver.protobuff;

/**
 * Protobuf type {@code ReservationsToAcceptCollection}
 */
public final class ReservationsToAcceptCollection extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:ReservationsToAcceptCollection)
    ReservationsToAcceptCollectionOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ReservationsToAcceptCollection.newBuilder() to construct.
  private ReservationsToAcceptCollection(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ReservationsToAcceptCollection() {
    reservationMessages_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ReservationsToAcceptCollection();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ReservationsToAcceptCollection(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              reservationMessages_ = new java.util.ArrayList<via.sep3.databaseserver.protobuff.ReservationMessage>();
              mutable_bitField0_ |= 0x00000001;
            }
            reservationMessages_.add(
                input.readMessage(via.sep3.databaseserver.protobuff.ReservationMessage.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (com.google.protobuf.UninitializedMessageException e) {
      throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        reservationMessages_ = java.util.Collections.unmodifiableList(reservationMessages_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return via.sep3.databaseserver.protobuff.Reservation.internal_static_ReservationsToAcceptCollection_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return via.sep3.databaseserver.protobuff.Reservation.internal_static_ReservationsToAcceptCollection_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            via.sep3.databaseserver.protobuff.ReservationsToAcceptCollection.class, via.sep3.databaseserver.protobuff.ReservationsToAcceptCollection.Builder.class);
  }

  public static final int RESERVATIONMESSAGES_FIELD_NUMBER = 1;
  private java.util.List<via.sep3.databaseserver.protobuff.ReservationMessage> reservationMessages_;
  /**
   * <code>repeated .ReservationMessage reservationMessages = 1;</code>
   */
  @java.lang.Override
  public java.util.List<via.sep3.databaseserver.protobuff.ReservationMessage> getReservationMessagesList() {
    return reservationMessages_;
  }
  /**
   * <code>repeated .ReservationMessage reservationMessages = 1;</code>
   */
  @java.lang.Override
  public java.util.List<? extends via.sep3.databaseserver.protobuff.ReservationMessageOrBuilder> 
      getReservationMessagesOrBuilderList() {
    return reservationMessages_;
  }
  /**
   * <code>repeated .ReservationMessage reservationMessages = 1;</code>
   */
  @java.lang.Override
  public int getReservationMessagesCount() {
    return reservationMessages_.size();
  }
  /**
   * <code>repeated .ReservationMessage reservationMessages = 1;</code>
   */
  @java.lang.Override
  public via.sep3.databaseserver.protobuff.ReservationMessage getReservationMessages(int index) {
    return reservationMessages_.get(index);
  }
  /**
   * <code>repeated .ReservationMessage reservationMessages = 1;</code>
   */
  @java.lang.Override
  public via.sep3.databaseserver.protobuff.ReservationMessageOrBuilder getReservationMessagesOrBuilder(
      int index) {
    return reservationMessages_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < reservationMessages_.size(); i++) {
      output.writeMessage(1, reservationMessages_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < reservationMessages_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, reservationMessages_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof via.sep3.databaseserver.protobuff.ReservationsToAcceptCollection)) {
      return super.equals(obj);
    }
    via.sep3.databaseserver.protobuff.ReservationsToAcceptCollection other = (via.sep3.databaseserver.protobuff.ReservationsToAcceptCollection) obj;

    if (!getReservationMessagesList()
        .equals(other.getReservationMessagesList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getReservationMessagesCount() > 0) {
      hash = (37 * hash) + RESERVATIONMESSAGES_FIELD_NUMBER;
      hash = (53 * hash) + getReservationMessagesList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static via.sep3.databaseserver.protobuff.ReservationsToAcceptCollection parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static via.sep3.databaseserver.protobuff.ReservationsToAcceptCollection parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static via.sep3.databaseserver.protobuff.ReservationsToAcceptCollection parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static via.sep3.databaseserver.protobuff.ReservationsToAcceptCollection parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static via.sep3.databaseserver.protobuff.ReservationsToAcceptCollection parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static via.sep3.databaseserver.protobuff.ReservationsToAcceptCollection parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static via.sep3.databaseserver.protobuff.ReservationsToAcceptCollection parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static via.sep3.databaseserver.protobuff.ReservationsToAcceptCollection parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static via.sep3.databaseserver.protobuff.ReservationsToAcceptCollection parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static via.sep3.databaseserver.protobuff.ReservationsToAcceptCollection parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static via.sep3.databaseserver.protobuff.ReservationsToAcceptCollection parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static via.sep3.databaseserver.protobuff.ReservationsToAcceptCollection parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(via.sep3.databaseserver.protobuff.ReservationsToAcceptCollection prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code ReservationsToAcceptCollection}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:ReservationsToAcceptCollection)
      via.sep3.databaseserver.protobuff.ReservationsToAcceptCollectionOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return via.sep3.databaseserver.protobuff.Reservation.internal_static_ReservationsToAcceptCollection_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return via.sep3.databaseserver.protobuff.Reservation.internal_static_ReservationsToAcceptCollection_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              via.sep3.databaseserver.protobuff.ReservationsToAcceptCollection.class, via.sep3.databaseserver.protobuff.ReservationsToAcceptCollection.Builder.class);
    }

    // Construct using via.sep3.databaseserver.protobuff.ReservationsToAcceptCollection.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getReservationMessagesFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (reservationMessagesBuilder_ == null) {
        reservationMessages_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        reservationMessagesBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return via.sep3.databaseserver.protobuff.Reservation.internal_static_ReservationsToAcceptCollection_descriptor;
    }

    @java.lang.Override
    public via.sep3.databaseserver.protobuff.ReservationsToAcceptCollection getDefaultInstanceForType() {
      return via.sep3.databaseserver.protobuff.ReservationsToAcceptCollection.getDefaultInstance();
    }

    @java.lang.Override
    public via.sep3.databaseserver.protobuff.ReservationsToAcceptCollection build() {
      via.sep3.databaseserver.protobuff.ReservationsToAcceptCollection result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public via.sep3.databaseserver.protobuff.ReservationsToAcceptCollection buildPartial() {
      via.sep3.databaseserver.protobuff.ReservationsToAcceptCollection result = new via.sep3.databaseserver.protobuff.ReservationsToAcceptCollection(this);
      int from_bitField0_ = bitField0_;
      if (reservationMessagesBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          reservationMessages_ = java.util.Collections.unmodifiableList(reservationMessages_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.reservationMessages_ = reservationMessages_;
      } else {
        result.reservationMessages_ = reservationMessagesBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof via.sep3.databaseserver.protobuff.ReservationsToAcceptCollection) {
        return mergeFrom((via.sep3.databaseserver.protobuff.ReservationsToAcceptCollection)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(via.sep3.databaseserver.protobuff.ReservationsToAcceptCollection other) {
      if (other == via.sep3.databaseserver.protobuff.ReservationsToAcceptCollection.getDefaultInstance()) return this;
      if (reservationMessagesBuilder_ == null) {
        if (!other.reservationMessages_.isEmpty()) {
          if (reservationMessages_.isEmpty()) {
            reservationMessages_ = other.reservationMessages_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureReservationMessagesIsMutable();
            reservationMessages_.addAll(other.reservationMessages_);
          }
          onChanged();
        }
      } else {
        if (!other.reservationMessages_.isEmpty()) {
          if (reservationMessagesBuilder_.isEmpty()) {
            reservationMessagesBuilder_.dispose();
            reservationMessagesBuilder_ = null;
            reservationMessages_ = other.reservationMessages_;
            bitField0_ = (bitField0_ & ~0x00000001);
            reservationMessagesBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getReservationMessagesFieldBuilder() : null;
          } else {
            reservationMessagesBuilder_.addAllMessages(other.reservationMessages_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      via.sep3.databaseserver.protobuff.ReservationsToAcceptCollection parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (via.sep3.databaseserver.protobuff.ReservationsToAcceptCollection) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<via.sep3.databaseserver.protobuff.ReservationMessage> reservationMessages_ =
      java.util.Collections.emptyList();
    private void ensureReservationMessagesIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        reservationMessages_ = new java.util.ArrayList<via.sep3.databaseserver.protobuff.ReservationMessage>(reservationMessages_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        via.sep3.databaseserver.protobuff.ReservationMessage, via.sep3.databaseserver.protobuff.ReservationMessage.Builder, via.sep3.databaseserver.protobuff.ReservationMessageOrBuilder> reservationMessagesBuilder_;

    /**
     * <code>repeated .ReservationMessage reservationMessages = 1;</code>
     */
    public java.util.List<via.sep3.databaseserver.protobuff.ReservationMessage> getReservationMessagesList() {
      if (reservationMessagesBuilder_ == null) {
        return java.util.Collections.unmodifiableList(reservationMessages_);
      } else {
        return reservationMessagesBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .ReservationMessage reservationMessages = 1;</code>
     */
    public int getReservationMessagesCount() {
      if (reservationMessagesBuilder_ == null) {
        return reservationMessages_.size();
      } else {
        return reservationMessagesBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .ReservationMessage reservationMessages = 1;</code>
     */
    public via.sep3.databaseserver.protobuff.ReservationMessage getReservationMessages(int index) {
      if (reservationMessagesBuilder_ == null) {
        return reservationMessages_.get(index);
      } else {
        return reservationMessagesBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .ReservationMessage reservationMessages = 1;</code>
     */
    public Builder setReservationMessages(
        int index, via.sep3.databaseserver.protobuff.ReservationMessage value) {
      if (reservationMessagesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureReservationMessagesIsMutable();
        reservationMessages_.set(index, value);
        onChanged();
      } else {
        reservationMessagesBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .ReservationMessage reservationMessages = 1;</code>
     */
    public Builder setReservationMessages(
        int index, via.sep3.databaseserver.protobuff.ReservationMessage.Builder builderForValue) {
      if (reservationMessagesBuilder_ == null) {
        ensureReservationMessagesIsMutable();
        reservationMessages_.set(index, builderForValue.build());
        onChanged();
      } else {
        reservationMessagesBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .ReservationMessage reservationMessages = 1;</code>
     */
    public Builder addReservationMessages(via.sep3.databaseserver.protobuff.ReservationMessage value) {
      if (reservationMessagesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureReservationMessagesIsMutable();
        reservationMessages_.add(value);
        onChanged();
      } else {
        reservationMessagesBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .ReservationMessage reservationMessages = 1;</code>
     */
    public Builder addReservationMessages(
        int index, via.sep3.databaseserver.protobuff.ReservationMessage value) {
      if (reservationMessagesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureReservationMessagesIsMutable();
        reservationMessages_.add(index, value);
        onChanged();
      } else {
        reservationMessagesBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .ReservationMessage reservationMessages = 1;</code>
     */
    public Builder addReservationMessages(
        via.sep3.databaseserver.protobuff.ReservationMessage.Builder builderForValue) {
      if (reservationMessagesBuilder_ == null) {
        ensureReservationMessagesIsMutable();
        reservationMessages_.add(builderForValue.build());
        onChanged();
      } else {
        reservationMessagesBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .ReservationMessage reservationMessages = 1;</code>
     */
    public Builder addReservationMessages(
        int index, via.sep3.databaseserver.protobuff.ReservationMessage.Builder builderForValue) {
      if (reservationMessagesBuilder_ == null) {
        ensureReservationMessagesIsMutable();
        reservationMessages_.add(index, builderForValue.build());
        onChanged();
      } else {
        reservationMessagesBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .ReservationMessage reservationMessages = 1;</code>
     */
    public Builder addAllReservationMessages(
        java.lang.Iterable<? extends via.sep3.databaseserver.protobuff.ReservationMessage> values) {
      if (reservationMessagesBuilder_ == null) {
        ensureReservationMessagesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, reservationMessages_);
        onChanged();
      } else {
        reservationMessagesBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .ReservationMessage reservationMessages = 1;</code>
     */
    public Builder clearReservationMessages() {
      if (reservationMessagesBuilder_ == null) {
        reservationMessages_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        reservationMessagesBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .ReservationMessage reservationMessages = 1;</code>
     */
    public Builder removeReservationMessages(int index) {
      if (reservationMessagesBuilder_ == null) {
        ensureReservationMessagesIsMutable();
        reservationMessages_.remove(index);
        onChanged();
      } else {
        reservationMessagesBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .ReservationMessage reservationMessages = 1;</code>
     */
    public via.sep3.databaseserver.protobuff.ReservationMessage.Builder getReservationMessagesBuilder(
        int index) {
      return getReservationMessagesFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .ReservationMessage reservationMessages = 1;</code>
     */
    public via.sep3.databaseserver.protobuff.ReservationMessageOrBuilder getReservationMessagesOrBuilder(
        int index) {
      if (reservationMessagesBuilder_ == null) {
        return reservationMessages_.get(index);  } else {
        return reservationMessagesBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .ReservationMessage reservationMessages = 1;</code>
     */
    public java.util.List<? extends via.sep3.databaseserver.protobuff.ReservationMessageOrBuilder> 
         getReservationMessagesOrBuilderList() {
      if (reservationMessagesBuilder_ != null) {
        return reservationMessagesBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(reservationMessages_);
      }
    }
    /**
     * <code>repeated .ReservationMessage reservationMessages = 1;</code>
     */
    public via.sep3.databaseserver.protobuff.ReservationMessage.Builder addReservationMessagesBuilder() {
      return getReservationMessagesFieldBuilder().addBuilder(
          via.sep3.databaseserver.protobuff.ReservationMessage.getDefaultInstance());
    }
    /**
     * <code>repeated .ReservationMessage reservationMessages = 1;</code>
     */
    public via.sep3.databaseserver.protobuff.ReservationMessage.Builder addReservationMessagesBuilder(
        int index) {
      return getReservationMessagesFieldBuilder().addBuilder(
          index, via.sep3.databaseserver.protobuff.ReservationMessage.getDefaultInstance());
    }
    /**
     * <code>repeated .ReservationMessage reservationMessages = 1;</code>
     */
    public java.util.List<via.sep3.databaseserver.protobuff.ReservationMessage.Builder> 
         getReservationMessagesBuilderList() {
      return getReservationMessagesFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        via.sep3.databaseserver.protobuff.ReservationMessage, via.sep3.databaseserver.protobuff.ReservationMessage.Builder, via.sep3.databaseserver.protobuff.ReservationMessageOrBuilder> 
        getReservationMessagesFieldBuilder() {
      if (reservationMessagesBuilder_ == null) {
        reservationMessagesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            via.sep3.databaseserver.protobuff.ReservationMessage, via.sep3.databaseserver.protobuff.ReservationMessage.Builder, via.sep3.databaseserver.protobuff.ReservationMessageOrBuilder>(
                reservationMessages_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        reservationMessages_ = null;
      }
      return reservationMessagesBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:ReservationsToAcceptCollection)
  }

  // @@protoc_insertion_point(class_scope:ReservationsToAcceptCollection)
  private static final via.sep3.databaseserver.protobuff.ReservationsToAcceptCollection DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new via.sep3.databaseserver.protobuff.ReservationsToAcceptCollection();
  }

  public static via.sep3.databaseserver.protobuff.ReservationsToAcceptCollection getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ReservationsToAcceptCollection>
      PARSER = new com.google.protobuf.AbstractParser<ReservationsToAcceptCollection>() {
    @java.lang.Override
    public ReservationsToAcceptCollection parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ReservationsToAcceptCollection(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ReservationsToAcceptCollection> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ReservationsToAcceptCollection> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public via.sep3.databaseserver.protobuff.ReservationsToAcceptCollection getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

