// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Reservation.proto

package via.sep3.databaseserver.protobuff;

public interface ReservationMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ReservationMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 rideId = 1;</code>
   * @return The rideId.
   */
  int getRideId();

  /**
   * <code>string name = 2;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 2;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string phone = 3;</code>
   * @return The phone.
   */
  java.lang.String getPhone();
  /**
   * <code>string phone = 3;</code>
   * @return The bytes for phone.
   */
  com.google.protobuf.ByteString
      getPhoneBytes();

  /**
   * <code>optional .BoolValue didAccept = 4;</code>
   * @return Whether the didAccept field is set.
   */
  boolean hasDidAccept();
  /**
   * <code>optional .BoolValue didAccept = 4;</code>
   * @return The didAccept.
   */
  via.sep3.databaseserver.protobuff.BoolValue getDidAccept();
  /**
   * <code>optional .BoolValue didAccept = 4;</code>
   */
  via.sep3.databaseserver.protobuff.BoolValueOrBuilder getDidAcceptOrBuilder();

  /**
   * <code>int32 id = 5;</code>
   * @return The id.
   */
  int getId();

  /**
   * <pre>
   *Maybe isAccepted?
   * </pre>
   *
   * <code>string status = 6;</code>
   * @return The status.
   */
  java.lang.String getStatus();
  /**
   * <pre>
   *Maybe isAccepted?
   * </pre>
   *
   * <code>string status = 6;</code>
   * @return The bytes for status.
   */
  com.google.protobuf.ByteString
      getStatusBytes();
}
