// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Rides.proto

package via.sep3.databaseserver.protobuff;

public interface RideIdMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:RideIdMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 rideId = 1;</code>
   * @return The rideId.
   */
  int getRideId();
}
