// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Rides.proto

package via.sep3.databaseserver.protobuff;

/**
 * Protobuf type {@code RidesCollection}
 */
public final class RidesCollection extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:RidesCollection)
    RidesCollectionOrBuilder {
private static final long serialVersionUID = 0L;
  // Use RidesCollection.newBuilder() to construct.
  private RidesCollection(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private RidesCollection() {
    rides_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new RidesCollection();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private RidesCollection(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              rides_ = new java.util.ArrayList<via.sep3.databaseserver.protobuff.RideMessage>();
              mutable_bitField0_ |= 0x00000001;
            }
            rides_.add(
                input.readMessage(via.sep3.databaseserver.protobuff.RideMessage.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (com.google.protobuf.UninitializedMessageException e) {
      throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        rides_ = java.util.Collections.unmodifiableList(rides_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return via.sep3.databaseserver.protobuff.RidesOuterClass.internal_static_RidesCollection_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return via.sep3.databaseserver.protobuff.RidesOuterClass.internal_static_RidesCollection_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            via.sep3.databaseserver.protobuff.RidesCollection.class, via.sep3.databaseserver.protobuff.RidesCollection.Builder.class);
  }

  public static final int RIDES_FIELD_NUMBER = 1;
  private java.util.List<via.sep3.databaseserver.protobuff.RideMessage> rides_;
  /**
   * <code>repeated .RideMessage rides = 1;</code>
   */
  @java.lang.Override
  public java.util.List<via.sep3.databaseserver.protobuff.RideMessage> getRidesList() {
    return rides_;
  }
  /**
   * <code>repeated .RideMessage rides = 1;</code>
   */
  @java.lang.Override
  public java.util.List<? extends via.sep3.databaseserver.protobuff.RideMessageOrBuilder> 
      getRidesOrBuilderList() {
    return rides_;
  }
  /**
   * <code>repeated .RideMessage rides = 1;</code>
   */
  @java.lang.Override
  public int getRidesCount() {
    return rides_.size();
  }
  /**
   * <code>repeated .RideMessage rides = 1;</code>
   */
  @java.lang.Override
  public via.sep3.databaseserver.protobuff.RideMessage getRides(int index) {
    return rides_.get(index);
  }
  /**
   * <code>repeated .RideMessage rides = 1;</code>
   */
  @java.lang.Override
  public via.sep3.databaseserver.protobuff.RideMessageOrBuilder getRidesOrBuilder(
      int index) {
    return rides_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < rides_.size(); i++) {
      output.writeMessage(1, rides_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < rides_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, rides_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof via.sep3.databaseserver.protobuff.RidesCollection)) {
      return super.equals(obj);
    }
    via.sep3.databaseserver.protobuff.RidesCollection other = (via.sep3.databaseserver.protobuff.RidesCollection) obj;

    if (!getRidesList()
        .equals(other.getRidesList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getRidesCount() > 0) {
      hash = (37 * hash) + RIDES_FIELD_NUMBER;
      hash = (53 * hash) + getRidesList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static via.sep3.databaseserver.protobuff.RidesCollection parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static via.sep3.databaseserver.protobuff.RidesCollection parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static via.sep3.databaseserver.protobuff.RidesCollection parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static via.sep3.databaseserver.protobuff.RidesCollection parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static via.sep3.databaseserver.protobuff.RidesCollection parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static via.sep3.databaseserver.protobuff.RidesCollection parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static via.sep3.databaseserver.protobuff.RidesCollection parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static via.sep3.databaseserver.protobuff.RidesCollection parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static via.sep3.databaseserver.protobuff.RidesCollection parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static via.sep3.databaseserver.protobuff.RidesCollection parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static via.sep3.databaseserver.protobuff.RidesCollection parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static via.sep3.databaseserver.protobuff.RidesCollection parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(via.sep3.databaseserver.protobuff.RidesCollection prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code RidesCollection}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:RidesCollection)
      via.sep3.databaseserver.protobuff.RidesCollectionOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return via.sep3.databaseserver.protobuff.RidesOuterClass.internal_static_RidesCollection_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return via.sep3.databaseserver.protobuff.RidesOuterClass.internal_static_RidesCollection_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              via.sep3.databaseserver.protobuff.RidesCollection.class, via.sep3.databaseserver.protobuff.RidesCollection.Builder.class);
    }

    // Construct using via.sep3.databaseserver.protobuff.RidesCollection.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getRidesFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (ridesBuilder_ == null) {
        rides_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        ridesBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return via.sep3.databaseserver.protobuff.RidesOuterClass.internal_static_RidesCollection_descriptor;
    }

    @java.lang.Override
    public via.sep3.databaseserver.protobuff.RidesCollection getDefaultInstanceForType() {
      return via.sep3.databaseserver.protobuff.RidesCollection.getDefaultInstance();
    }

    @java.lang.Override
    public via.sep3.databaseserver.protobuff.RidesCollection build() {
      via.sep3.databaseserver.protobuff.RidesCollection result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public via.sep3.databaseserver.protobuff.RidesCollection buildPartial() {
      via.sep3.databaseserver.protobuff.RidesCollection result = new via.sep3.databaseserver.protobuff.RidesCollection(this);
      int from_bitField0_ = bitField0_;
      if (ridesBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          rides_ = java.util.Collections.unmodifiableList(rides_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.rides_ = rides_;
      } else {
        result.rides_ = ridesBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof via.sep3.databaseserver.protobuff.RidesCollection) {
        return mergeFrom((via.sep3.databaseserver.protobuff.RidesCollection)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(via.sep3.databaseserver.protobuff.RidesCollection other) {
      if (other == via.sep3.databaseserver.protobuff.RidesCollection.getDefaultInstance()) return this;
      if (ridesBuilder_ == null) {
        if (!other.rides_.isEmpty()) {
          if (rides_.isEmpty()) {
            rides_ = other.rides_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureRidesIsMutable();
            rides_.addAll(other.rides_);
          }
          onChanged();
        }
      } else {
        if (!other.rides_.isEmpty()) {
          if (ridesBuilder_.isEmpty()) {
            ridesBuilder_.dispose();
            ridesBuilder_ = null;
            rides_ = other.rides_;
            bitField0_ = (bitField0_ & ~0x00000001);
            ridesBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getRidesFieldBuilder() : null;
          } else {
            ridesBuilder_.addAllMessages(other.rides_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      via.sep3.databaseserver.protobuff.RidesCollection parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (via.sep3.databaseserver.protobuff.RidesCollection) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<via.sep3.databaseserver.protobuff.RideMessage> rides_ =
      java.util.Collections.emptyList();
    private void ensureRidesIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        rides_ = new java.util.ArrayList<via.sep3.databaseserver.protobuff.RideMessage>(rides_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        via.sep3.databaseserver.protobuff.RideMessage, via.sep3.databaseserver.protobuff.RideMessage.Builder, via.sep3.databaseserver.protobuff.RideMessageOrBuilder> ridesBuilder_;

    /**
     * <code>repeated .RideMessage rides = 1;</code>
     */
    public java.util.List<via.sep3.databaseserver.protobuff.RideMessage> getRidesList() {
      if (ridesBuilder_ == null) {
        return java.util.Collections.unmodifiableList(rides_);
      } else {
        return ridesBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .RideMessage rides = 1;</code>
     */
    public int getRidesCount() {
      if (ridesBuilder_ == null) {
        return rides_.size();
      } else {
        return ridesBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .RideMessage rides = 1;</code>
     */
    public via.sep3.databaseserver.protobuff.RideMessage getRides(int index) {
      if (ridesBuilder_ == null) {
        return rides_.get(index);
      } else {
        return ridesBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .RideMessage rides = 1;</code>
     */
    public Builder setRides(
        int index, via.sep3.databaseserver.protobuff.RideMessage value) {
      if (ridesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureRidesIsMutable();
        rides_.set(index, value);
        onChanged();
      } else {
        ridesBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .RideMessage rides = 1;</code>
     */
    public Builder setRides(
        int index, via.sep3.databaseserver.protobuff.RideMessage.Builder builderForValue) {
      if (ridesBuilder_ == null) {
        ensureRidesIsMutable();
        rides_.set(index, builderForValue.build());
        onChanged();
      } else {
        ridesBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .RideMessage rides = 1;</code>
     */
    public Builder addRides(via.sep3.databaseserver.protobuff.RideMessage value) {
      if (ridesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureRidesIsMutable();
        rides_.add(value);
        onChanged();
      } else {
        ridesBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .RideMessage rides = 1;</code>
     */
    public Builder addRides(
        int index, via.sep3.databaseserver.protobuff.RideMessage value) {
      if (ridesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureRidesIsMutable();
        rides_.add(index, value);
        onChanged();
      } else {
        ridesBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .RideMessage rides = 1;</code>
     */
    public Builder addRides(
        via.sep3.databaseserver.protobuff.RideMessage.Builder builderForValue) {
      if (ridesBuilder_ == null) {
        ensureRidesIsMutable();
        rides_.add(builderForValue.build());
        onChanged();
      } else {
        ridesBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .RideMessage rides = 1;</code>
     */
    public Builder addRides(
        int index, via.sep3.databaseserver.protobuff.RideMessage.Builder builderForValue) {
      if (ridesBuilder_ == null) {
        ensureRidesIsMutable();
        rides_.add(index, builderForValue.build());
        onChanged();
      } else {
        ridesBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .RideMessage rides = 1;</code>
     */
    public Builder addAllRides(
        java.lang.Iterable<? extends via.sep3.databaseserver.protobuff.RideMessage> values) {
      if (ridesBuilder_ == null) {
        ensureRidesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, rides_);
        onChanged();
      } else {
        ridesBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .RideMessage rides = 1;</code>
     */
    public Builder clearRides() {
      if (ridesBuilder_ == null) {
        rides_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        ridesBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .RideMessage rides = 1;</code>
     */
    public Builder removeRides(int index) {
      if (ridesBuilder_ == null) {
        ensureRidesIsMutable();
        rides_.remove(index);
        onChanged();
      } else {
        ridesBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .RideMessage rides = 1;</code>
     */
    public via.sep3.databaseserver.protobuff.RideMessage.Builder getRidesBuilder(
        int index) {
      return getRidesFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .RideMessage rides = 1;</code>
     */
    public via.sep3.databaseserver.protobuff.RideMessageOrBuilder getRidesOrBuilder(
        int index) {
      if (ridesBuilder_ == null) {
        return rides_.get(index);  } else {
        return ridesBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .RideMessage rides = 1;</code>
     */
    public java.util.List<? extends via.sep3.databaseserver.protobuff.RideMessageOrBuilder> 
         getRidesOrBuilderList() {
      if (ridesBuilder_ != null) {
        return ridesBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(rides_);
      }
    }
    /**
     * <code>repeated .RideMessage rides = 1;</code>
     */
    public via.sep3.databaseserver.protobuff.RideMessage.Builder addRidesBuilder() {
      return getRidesFieldBuilder().addBuilder(
          via.sep3.databaseserver.protobuff.RideMessage.getDefaultInstance());
    }
    /**
     * <code>repeated .RideMessage rides = 1;</code>
     */
    public via.sep3.databaseserver.protobuff.RideMessage.Builder addRidesBuilder(
        int index) {
      return getRidesFieldBuilder().addBuilder(
          index, via.sep3.databaseserver.protobuff.RideMessage.getDefaultInstance());
    }
    /**
     * <code>repeated .RideMessage rides = 1;</code>
     */
    public java.util.List<via.sep3.databaseserver.protobuff.RideMessage.Builder> 
         getRidesBuilderList() {
      return getRidesFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        via.sep3.databaseserver.protobuff.RideMessage, via.sep3.databaseserver.protobuff.RideMessage.Builder, via.sep3.databaseserver.protobuff.RideMessageOrBuilder> 
        getRidesFieldBuilder() {
      if (ridesBuilder_ == null) {
        ridesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            via.sep3.databaseserver.protobuff.RideMessage, via.sep3.databaseserver.protobuff.RideMessage.Builder, via.sep3.databaseserver.protobuff.RideMessageOrBuilder>(
                rides_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        rides_ = null;
      }
      return ridesBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:RidesCollection)
  }

  // @@protoc_insertion_point(class_scope:RidesCollection)
  private static final via.sep3.databaseserver.protobuff.RidesCollection DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new via.sep3.databaseserver.protobuff.RidesCollection();
  }

  public static via.sep3.databaseserver.protobuff.RidesCollection getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<RidesCollection>
      PARSER = new com.google.protobuf.AbstractParser<RidesCollection>() {
    @java.lang.Override
    public RidesCollection parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new RidesCollection(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<RidesCollection> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<RidesCollection> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public via.sep3.databaseserver.protobuff.RidesCollection getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

