// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Users.proto

package via.sep3.databaseserver.protobuff;

public final class UsersOuterClass {
  private UsersOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_LicenseMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_LicenseMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_StatusMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_StatusMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CreateAccountMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CreateAccountMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_UserMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_UserMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_LoginMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_LoginMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_BoolMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_BoolMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_UsersMessageId_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_UsersMessageId_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013Users.proto\"3\n\016LicenseMessage\022\021\n\tlicen" +
      "seNo\030\001 \001(\005\022\016\n\006userId\030\002 \001(\005\"\037\n\rStatusMess" +
      "age\022\016\n\006status\030\001 \001(\010\"\200\001\n\024CreateAccountMes" +
      "sage\022\014\n\004name\030\001 \001(\t\022\026\n\tlicenseNo\030\002 \001(\005H\000\210" +
      "\001\001\022\023\n\013phoneNumber\030\003 \001(\005\022\r\n\005email\030\004 \001(\t\022\020" +
      "\n\010password\030\005 \001(\tB\014\n\n_licenseNo\"m\n\013UserMe" +
      "ssage\022\014\n\004name\030\001 \001(\t\022\023\n\013phoneNumber\030\002 \001(\005" +
      "\022\r\n\005email\030\003 \001(\t\022\032\n\rlicenseNumber\030\004 \001(\005H\000" +
      "\210\001\001B\020\n\016_licenseNumber\"/\n\014LoginMessage\022\r\n" +
      "\005email\030\001 \001(\t\022\020\n\010password\030\002 \001(\t\"S\n\013BoolMe" +
      "ssage\022\016\n\006status\030\001 \001(\010\022\016\n\006userId\030\002 \001(\005\022\026\n" +
      "\tlicenseNo\030\003 \001(\005H\000\210\001\001B\014\n\n_licenseNo\" \n\016U" +
      "sersMessageId\022\016\n\006userId\030\001 \001(\0052\301\001\n\005Users\022" +
      "4\n\rcreateAccount\022\025.CreateAccountMessage\032" +
      "\014.UserMessage\022$\n\005login\022\r.LoginMessage\032\014." +
      "BoolMessage\022*\n\tgetDriver\022\017.UsersMessageI" +
      "d\032\014.UserMessage\0220\n\rupdateLicense\022\017.Licen" +
      "seMessage\032\016.StatusMessageB%\n!via.sep3.da" +
      "tabaseserver.protobuffP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_LicenseMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_LicenseMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_LicenseMessage_descriptor,
        new java.lang.String[] { "LicenseNo", "UserId", });
    internal_static_StatusMessage_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_StatusMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_StatusMessage_descriptor,
        new java.lang.String[] { "Status", });
    internal_static_CreateAccountMessage_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_CreateAccountMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CreateAccountMessage_descriptor,
        new java.lang.String[] { "Name", "LicenseNo", "PhoneNumber", "Email", "Password", "LicenseNo", });
    internal_static_UserMessage_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_UserMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_UserMessage_descriptor,
        new java.lang.String[] { "Name", "PhoneNumber", "Email", "LicenseNumber", "LicenseNumber", });
    internal_static_LoginMessage_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_LoginMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_LoginMessage_descriptor,
        new java.lang.String[] { "Email", "Password", });
    internal_static_BoolMessage_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_BoolMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_BoolMessage_descriptor,
        new java.lang.String[] { "Status", "UserId", "LicenseNo", "LicenseNo", });
    internal_static_UsersMessageId_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_UsersMessageId_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_UsersMessageId_descriptor,
        new java.lang.String[] { "UserId", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
