// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Users.proto

package via.sep3.databaseserver.protobuff;

public interface UsersMessageIdOrBuilder extends
    // @@protoc_insertion_point(interface_extends:UsersMessageId)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 userId = 1;</code>
   * @return The userId.
   */
  int getUserId();
}
