// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Users.proto

package via.sep3.databaseserver.protobuff;

public interface UserMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:UserMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *not sure what we actually need on client side
   * </pre>
   *
   * <code>string name = 1;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <pre>
   *not sure what we actually need on client side
   * </pre>
   *
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>int32 phoneNumber = 2;</code>
   * @return The phoneNumber.
   */
  int getPhoneNumber();

  /**
   * <code>string email = 3;</code>
   * @return The email.
   */
  java.lang.String getEmail();
  /**
   * <code>string email = 3;</code>
   * @return The bytes for email.
   */
  com.google.protobuf.ByteString
      getEmailBytes();

  /**
   * <code>optional int32 licenseNumber = 4;</code>
   * @return Whether the licenseNumber field is set.
   */
  boolean hasLicenseNumber();
  /**
   * <code>optional int32 licenseNumber = 4;</code>
   * @return The licenseNumber.
   */
  int getLicenseNumber();
}
